# Generated by Django 6.1.1 on 2026-09-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='resume_pdf',
        ),
    ]
