# Generated by Django 6.1.1 on 2026-09-12 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_adminproject'),
        ('students', '0003_remove_studentprofile_resume_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_by', to='skills.adminproject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'project')},
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
