# Generated by Django 6.1.1 on 2026-09-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprojectselection_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.DateField(),
        ),
    ]
